apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  # namespace: application
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      # protocol: TCP
      port: {{ .Values.service.port }}
      # targetPort: {{ .Values.service.targetPort }}