appName: users-backend

container:
  name: users-api
  image: vasanthagokul/helm-dep-users
  tag: latest
  env:
    MONGODB_CONNECTION_URI: 'mongodb+srv://vasanthagokul:6RYjRHQdGoodZJ8t@cluster0.aqfurz0.mongodb.net/users?retryWrites=true&w=majority'
    AUTH_API_ADDRESS: 'auth-service.default:3000'

service:
  name: users-service
  # type: LoadBalancer
  type: ClusterIP
  port: 80
  # port: 3000
  targetPort: 3000


auth-backend:
  appName: auth-backend-via-users
